senz-server/README.md, serverInstallDebian.sh
-Added shell script for installing mongoDB and Scala on debian based operating systems.
-Updated the README.md for senz-server
-Tested twice
=> Added Shell Script and updated Readme

.dependabot/config.yml
Dependabot for managing packages
Closes issue #12
=> Adding dependabot 

senz-client-samples/python/README.md
=> Rectified the path in the README.md to Senz-Server

.dependabot/config.yml, senz-client-samples/rust/README.md, senz-client-samples/rust/rust-receiver/Cargo.lock, senz-client-samples/rust/rust-receiver/Cargo.toml, senz-client-samples/rust/rust-receiver/src/main.rs, senz-client-samples/rust/rust-sender/Cargo.lock, senz-client-samples/rust/rust-sender/Cargo.toml, senz-client-samples/rust/rust-sender/src/main.rs
Create receiver device for the ruby client sample
=> Implementing Ruby client sample 

senz-server/src/test/scala/com/scorelab/senz/MainTest.scala
This PR removes the extra lines from the MainTest.scala file.
=> related to #23- removed extra lines from MainTest.scala file

senz-client-samples/javascript/.eslintrc.json, senz-client-samples/javascript/README.md, senz-client-samples/javascript/package-lock.json, senz-client-samples/javascript/package.json
Added eslint in the javascript folder of the senz-client-samples to check for bad practices in javascript programming.
=> added eslint in the javascript folder in senz-client-samples

senz-server/src/main/scala/com/scorelab/senz/socket/SocketHandlerActor.scala
- Implemented the "UNSHARE Command" for the senz server.
```bash
UNSHARE #pubkey KEY @senz #time 1234 ^device_name signature
```
closes #38
=> Added UNSHARE command method

senz-client-samples/python/device_1/sender.py, senz-client-samples/python/device_2/receiver.py
- Added UNSHARE command to python clients.
- Allows continuous exchange of data.
closes #40
=> Adding unshare command to python

senz-client-samples/javascript/client.js, senz-client-samples/javascript/transfer_image/receiver.js, senz-client-samples/javascript/transfer_image/sender.js, senz-client-samples/javascript/utils/aes_utils.js, senz-client-samples/javascript/utils/image_utils.js
Removes var declarations and replaces it with the recommended const and let declarations
Fixes #55 
- Codebase improement
- [ x ] My PR follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code or materials
- [ x ] Any dependent changes have been merged
=> Remove var declarations in JS client

senz-web/frontend/package-lock.json, senz-web/frontend/src/components/App.js, senz-web/frontend/src/components/project/Analytics/Analytics.js, senz-web/frontend/src/components/project/Analytics/Devices.js, senz-web/frontend/src/components/project/Intro.js, senz-web/frontend/src/components/project/Settings/Form.js, senz-web/frontend/src/components/project/Settings/Settings.js
This PR includes code for -
- Analytics and Settings tab
=> Setup Analytics and Settings tab

senz-web/frontend/package-lock.json, senz-web/frontend/package.json, senz-web/frontend/src/components/App.js, senz-web/frontend/src/components/devices/AddDevice.js, senz-web/frontend/src/components/devices/AllDevices.js, senz-web/frontend/src/components/devices/DeviceList.js, senz-web/frontend/src/components/layout/Logout.js, senz-web/frontend/src/components/layout/SideBar.js, senz-web/frontend/src/components/project/AddProject.js, senz-web/frontend/src/components/project/AllProjects.js, senz-web/frontend/src/components/project/Analytics/Analytics.js, senz-web/frontend/src/components/project/Analytics/DeviceChart.js, senz-web/frontend/src/components/project/Analytics/Devices.js, senz-web/frontend/src/components/project/DashBoard/DashBoard.js, senz-web/frontend/src/components/project/DashBoard/Info.js, senz-web/frontend/src/components/project/DashBoard/NumDevices.js, senz-web/frontend/src/components/project/DashBoard/ProjectStat.js, senz-web/frontend/src/components/project/DashBoard/SentReceived.js, senz-web/frontend/src/components/project/Devices/ActionSelector.js, senz-web/frontend/src/components/project/Devices/Devices.js, senz-web/frontend/src/components/project/Devices/DevicesList.js, senz-web/frontend/src/components/project/Intro.js, senz-web/frontend/src/components/project/ProjectList.js, senz-web/frontend/src/components/project/Settings/Form.js, senz-web/frontend/src/components/project/Settings/Settings.js
closes #75 
Setup Video
https://drive.google.com/file/d/1BZc0pDO20j1Khsw0RlpyvDftxJeWunnm/view
=> Project and Device Component Setup

senz-web/backend/models/project.js, senz-web/backend/routes/projectRoutes.js, senz-web/frontend/package-lock.json, senz-web/frontend/package.json, senz-web/frontend/src/_actions/auth.js, senz-web/frontend/src/_actions/project.js, senz-web/frontend/src/_actions/types/index.js, senz-web/frontend/src/_reducers/authReducers.js, senz-web/frontend/src/_reducers/headingReducer.js, senz-web/frontend/src/_reducers/index.js, senz-web/frontend/src/_reducers/projectReducers.js, senz-web/frontend/src/components/App.js, senz-web/frontend/src/components/Loader.js, senz-web/frontend/src/components/layout/NavBar.js, senz-web/frontend/src/components/layout/NavDropDown.js, senz-web/frontend/src/components/project/AddProject.js, senz-web/frontend/src/components/project/AllProjects.js, senz-web/frontend/src/components/project/Analytics/Devices.js, senz-web/frontend/src/index.js
This PR has code for -
- Project reducers (fetching,adding,setting and deleting)
- redux-persist wrapper to maintain state even on refresh
- Altered project schema and an additional route for projects.
=> Setup project reducers and added redux-persist to maintain state

senz-web/frontend/src/_reducers/authReducers.test.js, senz-web/frontend/src/_reducers/deviceReducers.test.js, senz-web/frontend/src/_reducers/headingReducer.test.js, senz-web/frontend/src/_reducers/projectReducers.test.js, senz-web/frontend/src/components/authentication/Login.js, senz-web/frontend/src/components/authentication/Login.test.js, senz-web/frontend/src/components/authentication/Register.js, senz-web/frontend/src/components/authentication/Register.test.js, senz-web/frontend/src/components/devices/AddDevice.js, senz-web/frontend/src/components/devices/AddDevice.test.js, senz-web/frontend/src/components/devices/AllDevices.js, senz-web/frontend/src/components/devices/AllDevices.test.js, senz-web/frontend/src/components/devices/DeviceList.js, senz-web/frontend/src/components/devices/DeviceList.test.js, senz-web/frontend/src/components/layout/NavBar.js, senz-web/frontend/src/components/layout/NavBar.test.js, senz-web/frontend/src/components/layout/ProjectTab.js, senz-web/frontend/src/components/layout/ProjectTab.test.js, senz-web/frontend/src/components/layout/SideBar.js, senz-web/frontend/src/components/layout/SideBar.test.js, senz-web/frontend/src/components/project/Settings/Form.js, senz-web/frontend/src/components/project/Settings/Form.test.js
This PR contains code for-
- Unit tests of all reducers.
- Unit tests for projects,devices and auth components.
=> Tests for reducers,projects,devices and auth components

senz-web/backend/main.js, senz-web/backend/package.json, senz-web/backend/routes/deviceRoutes.js, senz-web/backend/routes/projectRoutes.js, senz-web/backend/test/device.js, senz-web/backend/test/project.js, senz-web/backend/test/user.js
- Added backend integration tests.
- Added pre-push git hook to the backend
closes #72
=> Backend tests

senz-client-samples/javascript/package.json, senz-switch/src/main/scala/com/scorelab/senz/database/MongoFactory.scala, senz-switch/src/main/scala/com/scorelab/senz/socket/SocketHandlerActor.scala
When the query is successfully executed it will log the sender and receiver along with the timestamp
=> Switch logger

senz-switch/build.sbt, senz-switch/src/main/scala/com/scorelab/senz/database/MongoFactory.scala, senz-switch/src/main/scala/com/scorelab/senz/socket/SocketHandlerActor.scala, senz-switch/src/main/scala/com/scorelab/senz/utils/ErrorHandling.scala
We needed a query checker for the senz switch that can maintain integrity with the senz web and throw detailed errors in case anything gets wrong.
Created mappings for the public key in #101 which are created and updated according to the senz-web.
This PR contains code that make the switch interact with those mappings and generate errors or allow switch actions.
=> Scala query checker

senz-web/backend/main.js, senz-web/backend/routes/deviceRoutes.js, senz-web/backend/routes/logRoutes.js, senz-web/frontend/src/__tests__/Intro.test.js, senz-web/frontend/src/_actions/log.js, senz-web/frontend/src/_actions/types/index.js, senz-web/frontend/src/_reducers/index.js, senz-web/frontend/src/_reducers/logReducers.js, senz-web/frontend/src/components/project/DashBoard/DashBoard.js, senz-web/frontend/src/components/project/DashBoard/NumDevices.js, senz-web/frontend/src/components/project/DashBoard/SentReceived.js
###Description
This PR contains code for -
- UI bug fixes.
- Analytics component.
=> Bug fixes and analytics component

nodejs-module/.gitignore, nodejs-module/README.md, nodejs-module/client/index.js, nodejs-module/client/switchFunc.js, nodejs-module/main.js, nodejs-module/package-lock.json, nodejs-module/package.json, nodejs-module/utils/aes_utils.js, nodejs-module/utils/image_utils.js, nodejs-module/utils/index.js, nodejs-module/utils/winstonConfig.js
This PR contains code for the npm module required for the senz.
It is hosted here
https://www.npmjs.com/package/senz
The upcoming PRs will refactor the code,include tests and will improve the documentation.
=> Setup npm module

.travis.yml, senz-web/backend/apidoc.json, senz-web/backend/package.json, senz-web/backend/routes/deviceRoutes.js, senz-web/backend/routes/logRoutes.js, senz-web/backend/routes/projectRoutes.js, senz-web/backend/routes/userRoutes.js
=> Documentaion and ci

senz-web/README.md, senz-web/backend/README.md, senz-web/frontend/README.md, senz-web/frontend/src/components/project/Analytics/InfoGraph.js
This PR contains code for 
- Bug fixes in the frontend.
- Documentation of the senz-web.
=> Bug fixes and documentation

nodejs-module/README.md, senz-web/frontend/src/components/App.js, senz-web/frontend/src/components/devices/AddDevice.js, senz-web/frontend/src/components/devices/AllDevices.js, senz-web/frontend/src/components/profile/EditProfile.js, senz-web/frontend/src/components/profile/ViewProfile.js, senz-web/frontend/src/components/project/AddProject.js, senz-web/frontend/src/components/project/AllProjects.js, senz-web/frontend/src/components/project/Analytics/Analytics.js, senz-web/frontend/src/components/project/DashBoard/DashBoard.js, senz-web/frontend/src/components/project/Devices/Devices.js, senz-web/frontend/src/components/project/Settings/Settings.js
This PR contains code for the following-
- Relevant card content of all the components.
- Fixed broken image in README.
=> Added card content

senz-web/frontend/src/components/authentication/Register.js
Standard password criteria has been set to make password strong.
Standard criteria includes: 
1- Minimum password length is 6.  
2- Password must contain atleast an uppercase letter 
3- Password must contain atleast an lowercase letter. 
4- Password must contain atleast a digit. 
5- Password must contain atleast a special character. (@,$,#,%,&)
Fixes #123 
I have added info icon besides Password , which when clicked will pop an alert screen which will inform the user about the above criteria. 
I have attached a screenshot which shows that all the tests have been passed and also I have attached a screenshots which shows the current changes.
Tests Passed Successfully : 
When password not satisfying given criteria :
When password is accepted :
When ```info icon``` is clicked :
=> Standard Password criteria has been implemented.

senz-web/frontend/src/components/authentication/Register.js
Fixed the sign-up button to be disabled when fields are not validated.
Fixes #124 
- Enhancement (non-breaking change which adds functionality)
=> Sign up button fixed according to issue #124

senz-web/backend/main.js, senz-web/backend/package.json
1.Add test coverage for the tests using Istanbul.js (open senz-web/backend/coverage/lcov-report/index.html) to view the rendered html.
2.Add mockgoose for mock database connection during testing.
Fixes #127 
=> Add test coverage using istanbul.js and Add mockgoose for mock database creation

senz-web/backend/models/user.js, senz-web/backend/package-lock.json, senz-web/backend/package.json, senz-web/backend/routes/userRoutes.js
Added the backend functionality for forgot password feature. Added nodemailer package for mailer purposes.
Fixes #126 
[senz-forgotpassword-testing.zip](https://github.com/scorelab/senz/files/4254517/senz-forgotpassword-testing.zip)
=> Add backend for forgot password feature

senz-web/backend/package.json, senz-web/backend/routes/userRoutes.js
Added the check to validate email address in backend for register and login.
New dependency added was email-validator.
Fixes # [125]
=> Email Checker for Backend (#125)

senz-web/frontend/src/components/authentication/Login.js
This is a very basic enhancement or I should say very trivial fix.  It fixes #145 
Earlier Sign In button was active all the time , even the email field is wrong or password field is empty.  Like shown in this screenshot : 
Password field is empty , still sign in button is active.
Email field is empty , still sign in button is active.
But now it will be active only when fields are valid , like this :
If invalid then it is inactive : 
Email field is missing then it is inactive : 
Password field is null then it is inactive : 
Active only when email field is valid  and password field is not null :
=> Login button status

senz-web/backend/routes/userRoutes.js, senz-web/backend/test/device.js, senz-web/backend/test/project.js, senz-web/backend/test/user.js
Now with one email, only one account be created. And test case for unique email check is added.
Fixes #147 
- Bug fix (non-breaking change which fixes an issue)
- fixed async clearing of database during unit testing after all test cases in each test module is completed.
=> Unique email check

senz-web/frontend/src/components/App.js
Once the user is logged in, he should not be allowed to login or register. But currently one can do so.
Fixes #151 
- Bug fix (non-breaking change which fixes an issue)
=> fix routes access post login

senz-web/frontend/src/__tests__/Login.test.js, senz-web/frontend/src/_actions/auth.js, senz-web/frontend/src/components/authentication/Login.js
Fixes #153 
- Bug fix (non-breaking change which fixes an issue)
=> fix issues on login screen

senz-web/backend/routes/deviceRoutes.js, senz-web/frontend/src/_actions/device.js, senz-web/frontend/src/_reducers/deviceReducers.js, senz-web/frontend/src/components/devices/AllDevices.js, senz-web/frontend/src/components/devices/DeviceList.js
The existing switch button was buggy and would lead to a bad user experience and would sometimes would cause unintended errors like switching off the device without even wanting to switch it off.
This change allows user to switch off only that device which is required with ease. Also I have fixed bugs which were not updating the status of devices in the projects.
Fixes #162 
[Toggle-devices.mov.zip](https://github.com/scorelab/senz/files/4327283/Toggle-devices.mov.zip)
=> Add toggle switches to toggle devices in place of a single switch button
